# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_tcn', models.CharField(default=b'idsiz', max_length=11)),
                ('student_name', models.CharField(default=b'isimsiz', max_length=200)),
                ('student_lastname', models.CharField(default=b'soysuz', max_length=200)),
                ('student_phone', phonenumber_field.modelfields.PhoneNumberField(default=b'+905553332211', max_length=128)),
                ('student_email', models.EmailField(default=b'qwe@gam.com', max_length=254)),
                ('student_bday', models.DateField(default=b'01/01/1990', verbose_name=b'Dogum Gunu')),
                ('student_regday', models.DateField(default=datetime.date.today, null=True)),
                ('student_city', models.CharField(choices=[(b'34', b'Istanbul'), (b'35', b'Izmir'), (b'06', b'Ankara')], default=b'Ankara', max_length=20, null=True)),
                ('student_town', models.CharField(default=b'yok', max_length=20, null=True)),
                ('student_adress', models.CharField(default=b'yok', max_length=50, null=True)),
                ('room_number', models.CharField(choices=[(b'2020403', b'403'), (b'2020402', b'402'), (b'2020401', b'401')], default=b'405', max_length=7, null=True)),
                ('student_type', models.CharField(choices=[(b'Misafir', b'Misafir'), (b'Gecici', b'Gecici'), (b'Normal', b'Normal')], default=b'Gecici', max_length=10)),
                ('birth_place', models.CharField(choices=[(b'34', b'Istanbul'), (b'35', b'Izmir'), (b'06', b'Ankara')], default=b'Ankara', max_length=20)),
                ('school_name', models.CharField(default=b'okulsuz', max_length=50)),
                ('education_year', models.CharField(choices=[(b'Prep', b'Preparation'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6')], default=b'1', max_length=20)),
                ('blood_type', models.CharField(choices=[(b'O rh +', b'0 rh +'), (b'0 rh -', b'0 rh -'), (b'A rh +', b'A rh +'), (b'A rh -', b'A rh -'), (b'B rh +', b'B rh +'), (b'B rh -', b'B rh -'), (b'AB rh +', b'AB rh+'), (b'AB rh -', b'AB rh-')], default=b'0 rh +', max_length=20)),
                ('health_notes', models.CharField(default=b'-', max_length=100, null=True)),
                ('special_notes', models.CharField(default=b'-', max_length=100, null=True)),
                ('file_field', models.FileField(default=None, null=True, upload_to=b'profile_pic/')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
