# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_email',
            field=models.EmailField(default=b'qwe@gam.com', help_text=b'aaaaa@aaaa.aaa', max_length=254, unique=True, verbose_name=b'Personal Email'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_tcn',
            field=models.CharField(default=b'00000000000', help_text=b'11 digit', max_length=11, unique=True, verbose_name=b'TC No'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_email',
            field=models.EmailField(default=b'qwe@gam.com', help_text=b'aaaaa@aaaa.aaa', max_length=254, unique=True, verbose_name=b'Student Email'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_tcn',
            field=models.CharField(default=b'00000000000', help_text=b'11 digit', max_length=11, unique=True, verbose_name=b'TC No'),
        ),
    ]
