# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(choices=[(1701001, 'Talha \xc7elik'), (1701002, 'isimsiz soysuz'), (1701003, 'isimsiz soysuz')])),
                ('parent_name', models.CharField(max_length=20)),
                ('parent_lastname', models.CharField(max_length=20)),
                ('parent_TCN', models.CharField(max_length=11)),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('parent_email', models.EmailField(max_length=254)),
                ('relative_degree', models.CharField(max_length=20)),
                ('parent_job', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'parent_info',
            },
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_bday',
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='student_birthday',
            field=models.DateField(default=b'1990-12-31', verbose_name=b'Dogum Gunu'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='birth_place',
            field=models.CharField(choices=[(b'01', b'Adana'), (b'02', b'Ad\xc4\xb1yaman'), (b'03', b'Afyon'), (b'04', b'A\xc4\x9fr\xc4\xb1'), (b'05', b'Amasya'), (b'06', b'Ankara'), (b'07', b'Antalya'), (b'08', b'Artvin'), (b'09', b'Ayd\xc4\xb1n'), (b'10', b'Bal\xc4\xb1kesir'), (b'11', b'Bilecik'), (b'12', b'Bing\xc3\xb6l'), (b'13', b'Bitlis'), (b'14', b'Bolu'), (b'15', b'Burdur'), (b'16', b'Bursa'), (b'17', b'\xc3\x87anakkale'), (b'18', b'\xc3\x87ank\xc4\xb1r\xc4\xb1'), (b'19', b'\xc3\x87orum'), (b'20', b'Denizli'), (b'21', b'Diyarbak\xc4\xb1r'), (b'22', b'Edirne'), (b'23', b'Elaz\xc4\xb1\xc4\x9f'), (b'24', b'Erzincan'), (b'25', b'Erzurum'), (b'26', b'Eski\xc5\x9fehir'), (b'27', b'Gaziantep'), (b'28', b'Giresun'), (b'29', b'G\xc3\xbcm\xc3\xbc\xc5\x9fhane'), (b'30', b'Hakkari'), (b'31', b'Hatay'), (b'32', b'Isparta'), (b'33', b'Mersin'), (b'34', b'\xc4\xb0stanbul'), (b'35', b'\xc4\xb0zmir'), (b'36', b'Kars'), (b'37', b'Kastamonu'), (b'38', b'Kayseri'), (b'39', b'K\xc4\xb1rklareli'), (b'40', b'K\xc4\xb1r\xc5\x9fehir'), (b'41', b'Kocaeli'), (b'42', b'Konya'), (b'43', b'K\xc3\xbctahya'), (b'44', b'Malatya'), (b'45', b'Manisa'), (b'46', b'Kahramanmara\xc5\x9f'), (b'47', b'Mardin'), (b'48', b'Mu\xc4\x9fla'), (b'49', b'Mu\xc5\x9f'), (b'50', b'Nev\xc5\x9fehir'), (b'51', b'Ni\xc4\x9fde'), (b'52', b'Ordu'), (b'53', b'Rize'), (b'54', b'Sakarya'), (b'55', b'Samsun'), (b'56', b'Siirt'), (b'57', b'Sinop'), (b'58', b'Sivas'), (b'59', b'Tekirda\xc4\x9f'), (b'60', b'Tokat'), (b'61', b'Trabzon'), (b'62', b'Tunceli'), (b'63', b'\xc5\x9eanl\xc4\xb1urfa'), (b'64', b'U\xc5\x9fak'), (b'65', b'Van'), (b'66', b'Yozgat'), (b'67', b'Zonguldak'), (b'68', b'Aksaray'), (b'69', b'Bayburt'), (b'70', b'Karaman'), (b'71', b'K\xc4\xb1r\xc4\xb1kkale'), (b'72', b'Batman'), (b'73', b'\xc5\x9e\xc4\xb1rnak'), (b'74', b'Bart\xc4\xb1n'), (b'75', b'Ardahan'), (b'76', b'I\xc4\x9fd\xc4\xb1r'), (b'77', b'Yalova'), (b'78', b'Karab\xc3\xbck'), (b'79', b'Kilis'), (b'80', b'Osmaniye'), (b'81', b'D\xc3\xbczce')], default=b'Ankara', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_city',
            field=models.CharField(choices=[(b'01', b'Adana'), (b'02', b'Ad\xc4\xb1yaman'), (b'03', b'Afyon'), (b'04', b'A\xc4\x9fr\xc4\xb1'), (b'05', b'Amasya'), (b'06', b'Ankara'), (b'07', b'Antalya'), (b'08', b'Artvin'), (b'09', b'Ayd\xc4\xb1n'), (b'10', b'Bal\xc4\xb1kesir'), (b'11', b'Bilecik'), (b'12', b'Bing\xc3\xb6l'), (b'13', b'Bitlis'), (b'14', b'Bolu'), (b'15', b'Burdur'), (b'16', b'Bursa'), (b'17', b'\xc3\x87anakkale'), (b'18', b'\xc3\x87ank\xc4\xb1r\xc4\xb1'), (b'19', b'\xc3\x87orum'), (b'20', b'Denizli'), (b'21', b'Diyarbak\xc4\xb1r'), (b'22', b'Edirne'), (b'23', b'Elaz\xc4\xb1\xc4\x9f'), (b'24', b'Erzincan'), (b'25', b'Erzurum'), (b'26', b'Eski\xc5\x9fehir'), (b'27', b'Gaziantep'), (b'28', b'Giresun'), (b'29', b'G\xc3\xbcm\xc3\xbc\xc5\x9fhane'), (b'30', b'Hakkari'), (b'31', b'Hatay'), (b'32', b'Isparta'), (b'33', b'Mersin'), (b'34', b'\xc4\xb0stanbul'), (b'35', b'\xc4\xb0zmir'), (b'36', b'Kars'), (b'37', b'Kastamonu'), (b'38', b'Kayseri'), (b'39', b'K\xc4\xb1rklareli'), (b'40', b'K\xc4\xb1r\xc5\x9fehir'), (b'41', b'Kocaeli'), (b'42', b'Konya'), (b'43', b'K\xc3\xbctahya'), (b'44', b'Malatya'), (b'45', b'Manisa'), (b'46', b'Kahramanmara\xc5\x9f'), (b'47', b'Mardin'), (b'48', b'Mu\xc4\x9fla'), (b'49', b'Mu\xc5\x9f'), (b'50', b'Nev\xc5\x9fehir'), (b'51', b'Ni\xc4\x9fde'), (b'52', b'Ordu'), (b'53', b'Rize'), (b'54', b'Sakarya'), (b'55', b'Samsun'), (b'56', b'Siirt'), (b'57', b'Sinop'), (b'58', b'Sivas'), (b'59', b'Tekirda\xc4\x9f'), (b'60', b'Tokat'), (b'61', b'Trabzon'), (b'62', b'Tunceli'), (b'63', b'\xc5\x9eanl\xc4\xb1urfa'), (b'64', b'U\xc5\x9fak'), (b'65', b'Van'), (b'66', b'Yozgat'), (b'67', b'Zonguldak'), (b'68', b'Aksaray'), (b'69', b'Bayburt'), (b'70', b'Karaman'), (b'71', b'K\xc4\xb1r\xc4\xb1kkale'), (b'72', b'Batman'), (b'73', b'\xc5\x9e\xc4\xb1rnak'), (b'74', b'Bart\xc4\xb1n'), (b'75', b'Ardahan'), (b'76', b'I\xc4\x9fd\xc4\xb1r'), (b'77', b'Yalova'), (b'78', b'Karab\xc3\xbck'), (b'79', b'Kilis'), (b'80', b'Osmaniye'), (b'81', b'D\xc3\xbczce')], default=b'Ankara', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_tcn',
            field=models.CharField(default=b'idsiz', max_length=11, verbose_name=b'TC No: Olala!'),
        ),
    ]
