# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_auto_20170617_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='parentinfomodel',
            name='id',
            field=models.CharField(default=django.utils.timezone.now, help_text=b'Parent Id', max_length=50, primary_key=True, serialize=False, verbose_name=b'Parent Id: '),
            preserve_default=False,
        ),
    ]
