# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0002_auto_20170520_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfomodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.IntegerField(choices=[(1701001, 'Talha \xc7elik'), (1701002, 'isimsiz soysuz'), (1701003, 'isimsiz soysuz')], primary_key=True, serialize=False),
        ),
    ]
