# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0003_auto_20170617_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.CharField(max_length=7),
        ),
    ]
