# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0003_auto_20170520_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.IntegerField(choices=[(1701001, 'Talha \xc7elik'), (1701002, 'isimsiz soysuz'), (1701003, 'isimsiz soysuz'), (1701004, 'isimsiz soysuz'), (1701005, 'isimsiz soysuz')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_name',
            field=models.CharField(default=b'isimsiz', max_length=200, verbose_name=b'Student Name:'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_tcn',
            field=models.CharField(default=b'idsiz', max_length=11, verbose_name=b'TC No: '),
        ),
    ]
