# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0004_auto_20170617_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='id',
            field=models.CharField(help_text=b'Parent Id', max_length=50, primary_key=True, verbose_name=b'Parent Id: '),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
