# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0004_auto_20170521_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_number',
            field=models.CharField(default=b'405', max_length=7, null=True),
        ),
    ]
