# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0006_auto_20170617_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpanel.StudentInfoModel'),
        ),
    ]
