# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpanel', '0006_auto_20170521_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_number',
            field=models.CharField(choices=[(1, '101'), (2, '102'), (3, '103'), (4, '201'), (5, '202'), (6, '203'), (7, '301'), (8, '302'), (9, '303'), (10, '401'), (11, '402'), (12, '403')], default=b'405', max_length=7, null=True),
        ),
    ]
