# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureInfoModel',
            fields=[
                ('no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('image_field', models.ImageField(default='', upload_to='fixture_image/')),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fixture_info',
            },
        ),
        migrations.CreateModel(
            name='RoomInfoModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('no', models.CharField(default='', max_length=4)),
                ('floor', models.CharField(blank=True, max_length=2, null=True)),
                ('people', models.CharField(choices=[('1', 'Tek Kişilik'), ('2', 'İki Kişilik'), ('3', 'Üç Kişilik'), ('4', 'Dört Kişilik'), ('5', 'Beş Kişilik')], max_length=2)),
                ('type', models.CharField(choices=[('1', 'Duşakabin'), ('2', 'Ranzalı'), ('3', 'Normal'), ('4', 'Mutfaklı')], max_length=20)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
    ]
