# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureInfoModel',
            fields=[
                ('no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Fixture No: ')),
                ('room', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=20, verbose_name='Fixture Type:')),
                ('notes', models.CharField(blank=True, default='', max_length=100, verbose_name='Fixture Notes: ')),
                ('image_field', models.ImageField(blank=True, default='', upload_to='fixture_image/', verbose_name='Fixture Image: ')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'fixture_info',
            },
        ),
        migrations.CreateModel(
            name='RoomInfoModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='room ID')),
                ('no', models.CharField(max_length=4, verbose_name='Room No: ')),
                ('floor', models.CharField(default='', max_length=2, verbose_name='Room Floor: ')),
                ('people', models.CharField(choices=[('1', 'Tek Kişilik'), ('2', 'İki Kişilik'), ('3', 'Üç Kişilik'), ('4', 'Dört Kişilik'), ('5', 'Beş Kişilik')], max_length=2, verbose_name='Room People: ')),
                ('type', models.CharField(choices=[('1', 'Duşakabin'), ('2', 'Ranzalı'), ('3', 'Normal'), ('4', 'Mutfaklı')], max_length=20, verbose_name='Room Type: ')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Room Description')),
                ('image_field', models.ImageField(blank=True, default='', upload_to='room_image/', verbose_name='Room Image: ')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
    ]
