# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureInfoModel',
            fields=[
                ('fixture_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name=b'Fixture No: ')),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('fixture_type', models.CharField(choices=[(b'1', b'Box Spring'), (b'2', b'Bed'), (b'3', b'Wardrobe'), (b'4', b'Carpet'), (b'5', b'Night Stand'), (b'6', b'Tulle'), (b'7', b'Veil'), (b'8', b'Table'), (b'9', b'Chair'), (b'10', b'Coat Hanger'), (b'11', b'Bookcase'), (b'12', b'Lamp'), (b'13', b'Klima'), (b'14', b'Mirror')], max_length=20, verbose_name=b'Fixture Type:')),
                ('fixture_notes', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Fixture Notes: ')),
                ('fixture_image', models.ImageField(blank=True, default=None, null=True, upload_to=b'fixture_image/', verbose_name=b'Fixture Image: ')),
            ],
            options={
                'db_table': 'fixture_info',
            },
        ),
        migrations.CreateModel(
            name='LiabilityInfoModel',
            fields=[
                ('record_no', models.CharField(default=b'1', max_length=10, primary_key=True, serialize=False, verbose_name=b'Record No: ')),
                ('person_id', models.CharField(blank=True, max_length=10, null=True)),
                ('liability_type', models.CharField(choices=[(b'1', b'Box Spring'), (b'2', b'Bed'), (b'3', b'Wardrobe'), (b'4', b'Carpet'), (b'5', b'Night Stand'), (b'6', b'Tulle'), (b'7', b'Veil'), (b'8', b'Table'), (b'9', b'Chair'), (b'10', b'Coat Hanger'), (b'11', b'Bookcase'), (b'12', b'Lamp'), (b'13', b'Klima'), (b'14', b'Mirror')], max_length=50, verbose_name=b'Liability Type: ')),
                ('liability_name', models.CharField(max_length=50, verbose_name=b'Liability Name: ')),
                ('liability_desc', models.CharField(max_length=100, verbose_name=b'Liability Description: ')),
                ('liability_date', models.DateField(default=datetime.date.today, verbose_name=b'Liability Day')),
                ('liability_lastday', models.DateField(blank=True, default=datetime.datetime(2017, 7, 17, 18, 13, 45, 537000), null=True, verbose_name=b'Liability Last day')),
                ('liability_return', models.DateField(blank=True, null=True, verbose_name=b'Liability Return day')),
                ('liability_penalty', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'liability_info',
            },
        ),
        migrations.CreateModel(
            name='RoomInfoModel',
            fields=[
                ('room_no', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name=b'Room No: ')),
                ('room_floor', models.CharField(max_length=20, verbose_name=b'Room Floor: ')),
                ('room_people', models.CharField(choices=[(b'1', b'One Person'), (b'2', b'Two People'), (b'3', b'Three People'), (b'4', b'Four People'), (b'5', b'Five People')], max_length=20, verbose_name=b'Room People: ')),
                ('room_type', models.CharField(choices=[(b'1', b'With Shower'), (b'2', b'Double-Decker'), (b'3', b'Normal'), (b'4', b'Kitchen')], max_length=20, verbose_name=b'Room Type: ')),
                ('room_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Room Description')),
                ('room_image', models.ImageField(blank=True, default=None, null=True, upload_to=b'room_image/', verbose_name=b'Room Image: ')),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
    ]
