# Generated by Django 2.0.1 on 2018-01-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel'),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
    ]
