# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel'),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
    ]
