# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0002_auto_20171030_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='fixture_image/'),
        ),
    ]
