# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0003_auto_20170710_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='room_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name=b'Room No: '),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 18, 9, 59, 2, 355000), null=True, verbose_name=b'Liability Last day'),
        ),
    ]
