# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0005_auto_20170711_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 18, 12, 24, 13, 815000), null=True, verbose_name=b'Liability Last day'),
        ),
    ]
