# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0005_auto_20171003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='image_field',
            field=models.ImageField(default='', upload_to='fixture_image/'),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel'),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='floor',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='image_field',
            field=models.ImageField(default='', upload_to='room_image/'),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='no',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='people',
            field=models.CharField(choices=[('1', 'Tek Kişilik'), ('2', 'İki Kişilik'), ('3', 'Üç Kişilik'), ('4', 'Dört Kişilik'), ('5', 'Beş Kişilik')], max_length=2),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Duşakabin'), ('2', 'Ranzalı'), ('3', 'Normal'), ('4', 'Mutfaklı')], max_length=20),
        ),
    ]
