# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0006_auto_20171018_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roominfomodel',
            name='image_field',
        ),
    ]
