# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0011_auto_20170713_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiabilityInfoModel',
        ),
    ]
