# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0012_delete_liabilityinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='fixture_image/', verbose_name='Fixture Image: '),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Fixture No: '),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fixture Notes: '),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_type',
            field=models.CharField(choices=[('1', 'Box Spring'), ('2', 'Bed'), ('3', 'Wardrobe'), ('4', 'Carpet'), ('5', 'Night Stand'), ('6', 'Tulle'), ('7', 'Veil'), ('8', 'Table'), ('9', 'Chair'), ('10', 'Coat Hanger'), ('11', 'Bookcase'), ('12', 'Lamp'), ('13', 'Klima'), ('14', 'Mirror')], max_length=20, verbose_name='Fixture Type:'),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='room_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name='Room No: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Room Description'),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_floor',
            field=models.CharField(max_length=20, verbose_name='Room Floor: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='room_image/', verbose_name='Room Image: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Room No: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_people',
            field=models.CharField(choices=[('1', 'One Person'), ('2', 'Two People'), ('3', 'Three People'), ('4', 'Four People'), ('5', 'Five People')], max_length=20, verbose_name='Room People: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_type',
            field=models.CharField(choices=[('1', 'With Shower'), ('2', 'Double-Decker'), ('3', 'Normal'), ('4', 'Kitchen')], max_length=20, verbose_name='Room Type: '),
        ),
    ]
