# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0013_auto_20170714_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_people',
            field=models.CharField(default='0', max_length=20, verbose_name='Room People: '),
        ),
    ]
