# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0014_auto_20170716_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_people',
            field=models.CharField(choices=[('1', 'One Person'), ('2', 'Two People'), ('3', 'Three People'), ('4', 'Four People'), ('5', 'Five People')], max_length=20, verbose_name='Room People: '),
        ),
    ]
