# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_panel', '0015_auto_20170716_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_image',
            field=models.ImageField(blank=True, default='', upload_to='fixture_image/', verbose_name='Fixture Image: '),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_notes',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fixture Notes: '),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='fixture_type',
            field=models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=20, verbose_name='Fixture Type:'),
        ),
        migrations.AlterField(
            model_name='fixtureinfomodel',
            name='room_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name='Room No: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_desc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Room Description'),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_floor',
            field=models.CharField(default='', max_length=2, verbose_name='Room Floor: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_image',
            field=models.ImageField(blank=True, default='', upload_to='room_image/', verbose_name='Room Image: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_no',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Room No: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_people',
            field=models.CharField(choices=[('1', 'Tek Kişilik'), ('2', 'İki Kişilik'), ('3', 'Üç Kişilik'), ('4', 'Dört Kişilik'), ('5', 'Beş Kişilik')], max_length=2, verbose_name='Room People: '),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_type',
            field=models.CharField(choices=[('1', 'Duşakabin'), ('2', 'Ranzalı'), ('3', 'Normal'), ('4', 'Mutfaklı')], max_length=20, verbose_name='Room Type: '),
        ),
    ]
