# Generated by Django 2.0.1 on 2018-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Adsız Etkinlik', max_length=30)),
                ('start_time', models.DateTimeField(default='')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.NullBooleanField()),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('0', 'Doğum Günü'), ('1', 'Toplantı'), ('2', 'Diğer')], max_length=10, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'event_info',
            },
        ),
    ]
