# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import user_panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=13)),
                ('date_joined', models.DateField(default=user_panel.models.get_date, max_length=10)),
                ('date_expired', models.DateField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(default='profile_pic/1701001', max_length=200, upload_to='')),
                ('company_id', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfoModel',
            fields=[
                ('company_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=20)),
                ('company_vno', models.CharField(default='', max_length=15)),
                ('company_adress', models.CharField(blank=True, max_length=100, null=True)),
                ('company_account_no', models.CharField(blank=True, max_length=15, null=True)),
                ('company_payment_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('company_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyModel',
            fields=[
                ('user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user_company',
            },
        ),
    ]
