# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(max_length=10),
        ),
    ]
