# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20171003_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanymodel',
            name='company',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usercompanymodel',
            name='user',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
