# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20171030_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.CharField(default='171911001', max_length=20),
        ),
    ]
