# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_auto_20171030_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_pic/1701001.jpg', max_length=200, upload_to=''),
        ),
    ]
