# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_auto_20171031_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_pic/1701001.jpg', max_length=200, upload_to=''),
        ),
    ]
