# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_auto_20171101_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
    ]
