# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_auto_20171003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfomodel',
            name='company_account_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfomodel',
            name='company_adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfomodel',
            name='company_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfomodel',
            name='company_payment_detail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
