# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0006_auto_20171018_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_pic/1701001', max_length=200, upload_to=''),
        ),
    ]
