# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfoModel',
            fields=[
                ('document_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Document Id: ')),
                ('person_id', models.CharField(max_length=7, verbose_name='Person Id: ')),
                ('document_date', models.DateField(default=datetime.date.today, verbose_name='Document Record Date: ')),
                ('document_type', models.CharField(choices=[('01', 'ID Card'), ('02', 'Insurance'), ('03', 'Bill'), ('04', 'Leave Doc.'), ('05', 'Student Certificate')], max_length=20, verbose_name='Document Type: ')),
                ('document_description', models.CharField(blank=True, max_length=100, verbose_name='Documnet Description: ')),
                ('document_image', models.ImageField(default='Desktop/asd.jpg', upload_to='document_image/', verbose_name='Documnet Image or Scan')),
            ],
            options={
                'db_table': 'documnet_info',
            },
        ),
    ]
