# Generated by Django 2.0.1 on 2018-01-14 19:32

from django.db import migrations, models
import document_panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('1', 'Kimlik Kartı'), ('2', 'Sigorta'), ('3', 'Fatura'), ('4', 'İzin Kağıdı'), ('5', 'Öğrenci Sertifikası')], max_length=20)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('image_field', models.ImageField(upload_to='document_image/')),
                ('company', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'document_info',
            },
        ),
        migrations.CreateModel(
            name='LiabilityInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=50)),
                ('desc', models.CharField(blank=True, default='', max_length=100)),
                ('give_day', models.DateTimeField(default=document_panel.models.get_time, max_length=20)),
                ('last_day', models.DateTimeField(blank=True, max_length=20, null=True)),
                ('take_day', models.DateTimeField(blank=True, null=True)),
                ('penalty', models.CharField(blank=True, default='0.0', max_length=30)),
                ('company', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'liability_info',
            },
        ),
    ]
