# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import document_panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInfoModel',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Document Id: ')),
                ('person', models.CharField(max_length=7, verbose_name='Person Id: ')),
                ('date', models.DateField(default=document_panel.models.get_date, max_length=10, verbose_name='Document Record Date: ')),
                ('type', models.CharField(choices=[('1', 'Kimlik Kartı'), ('2', 'Sigorta'), ('3', 'Fatura'), ('4', 'İzin Kağıdı'), ('5', 'Öğrenci Sertifikası')], max_length=20, verbose_name='Document Type: ')),
                ('desc', models.CharField(default='', max_length=100, verbose_name='Documnet Description: ')),
                ('image_field', models.ImageField(blank=True, default='', upload_to='document_image/', verbose_name='Documnet Image or Scan')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'documnet_info',
            },
        ),
        migrations.CreateModel(
            name='LiabilityInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=50, verbose_name='Liability Type: ')),
                ('desc', models.CharField(blank=True, default='', max_length=100, verbose_name='Liability Description: ')),
                ('give_day', models.DateTimeField(default='', max_length=20, verbose_name='Liability Day')),
                ('last_day', models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='Liability Last day')),
                ('take_day', models.DateTimeField(blank=True, null=True, verbose_name='Liability Return day')),
                ('penalty', models.CharField(blank=True, default='', max_length=30)),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'liability_info',
            },
        ),
    ]
