# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfomodel',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Person id: '),
        ),
    ]
