# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0002_auto_20170711_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_type',
            field=models.CharField(choices=[('1', 'ID Card'), ('2', 'Insurance'), ('3', 'Bill'), ('4', 'Leave Doc.'), ('5', 'Student Certificate')], max_length=20, verbose_name='Document Type: '),
        ),
    ]
