# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0002_auto_20170711_1001'),
        ('document_panel', '0003_auto_20170711_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilityInfoModel',
            fields=[
                ('record_no', models.CharField(default='1', max_length=10, primary_key=True, serialize=False, verbose_name='Record No: ')),
                ('liability_type', models.CharField(choices=[('1', 'Box Spring'), ('2', 'Bed'), ('3', 'Wardrobe'), ('4', 'Carpet'), ('5', 'Night Stand'), ('6', 'Tulle'), ('7', 'Veil'), ('8', 'Table'), ('9', 'Chair'), ('10', 'Coat Hanger'), ('11', 'Bookcase'), ('12', 'Lamp'), ('13', 'Klima'), ('14', 'Mirror')], max_length=50, verbose_name='Liability Type: ')),
                ('liability_name', models.CharField(max_length=50, verbose_name='Liability Name: ')),
                ('liability_desc', models.CharField(max_length=100, verbose_name='Liability Description: ')),
                ('liability_date', models.DateField(default=datetime.date.today, verbose_name='Liability Day')),
                ('liability_lastday', models.DateField(blank=True, default=datetime.datetime(2017, 7, 20, 13, 12, 45, 436000), null=True, verbose_name='Liability Last day')),
                ('liability_return', models.DateField(blank=True, null=True, verbose_name='Liability Return day')),
                ('liability_penalty', models.CharField(blank=True, max_length=30, null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Person Id: ')),
            ],
            options={
                'db_table': 'liability_info',
            },
        ),
    ]
