# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0004_liabilityinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 20, 14, 39, 22, 866000), null=True, verbose_name='Liability Last day'),
        ),
    ]
