# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0005_auto_20171003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='company_id',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
    ]
