# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0006_auto_20171004_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfomodel',
            name='date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='image_field',
            field=models.ImageField(upload_to='document_image/'),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Kimlik Kartı'), ('2', 'Sigorta'), ('3', 'Fatura'), ('4', 'İzin Kağıdı'), ('5', 'Öğrenci Sertifikası')], max_length=20),
        ),
    ]
