# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0007_auto_20171009_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='give_day',
            field=models.DateTimeField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='last_day',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='take_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=50),
        ),
    ]
