# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0011_auto_20170716_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 23, 17, 52, 40, 631649), null=True, verbose_name='Liability Last day'),
        ),
    ]
