# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0013_auto_20170717_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 26, 17, 14, 22, 159047), null=True, verbose_name='Liability Last day'),
        ),
    ]
