# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0014_auto_20170719_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 27, 21, 6, 38, 388456), null=True, verbose_name='Liability Last day'),
        ),
    ]
