# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import document_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0016_auto_20170721_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_date',
            field=models.DateTimeField(default=document_panel.models.get_time, verbose_name='Document Record Date: '),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_date',
            field=models.DateTimeField(default=document_panel.models.get_time, verbose_name='Liability Day'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateTimeField(blank=True, default=document_panel.models.get_time, null=True, verbose_name='Liability Last day'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Liability Return day'),
        ),
    ]
