# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0017_auto_20170721_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilityinfomodel',
            name='record_no',
        ),
        migrations.AddField(
            model_name='liabilityinfomodel',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_description',
            field=models.CharField(default='', max_length=100, verbose_name='Documnet Description: '),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, verbose_name='Document Id: '),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_image',
            field=models.ImageField(default='', upload_to='document_image/', verbose_name='Documnet Image or Scan'),
        ),
    ]
