# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import document_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0018_auto_20170729_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilityinfomodel',
            name='liability_name',
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_type',
            field=models.CharField(choices=[('1', 'Kimlik Kartı'), ('2', 'Sigorta'), ('3', 'Fatura'), ('4', 'İzin Kağıdı'), ('5', 'Öğrenci Sertifikası')], max_length=20, verbose_name='Document Type: '),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_desc',
            field=models.CharField(default='', max_length=100, verbose_name='Liability Description: '),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateTimeField(blank=True, default=document_panel.models.get_time, verbose_name='Liability Last day'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_penalty',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_return',
            field=models.DateTimeField(blank=True, verbose_name='Liability Return day'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_type',
            field=models.CharField(choices=[('1', 'Baza'), ('2', 'Yatak'), ('3', 'Dolap'), ('4', 'Halı'), ('5', 'Komodin'), ('6', 'Tül'), ('7', 'Perde'), ('8', 'Masa'), ('9', 'Sandalye'), ('10', 'Askılık'), ('11', 'Kitaplık'), ('12', 'Lamba'), ('13', 'Klima'), ('14', 'Ayna')], max_length=50, verbose_name='Liability Type: '),
        ),
    ]
