# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import document_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0019_auto_20170729_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_date',
            field=models.DateField(default=document_panel.models.get_date, verbose_name='Document Record Date: '),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_return',
            field=models.DateTimeField(blank=True, default='', verbose_name='Liability Return day'),
        ),
    ]
