# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import document_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('document_panel', '0020_auto_20170731_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_date',
            field=models.DateField(default=document_panel.models.get_date, max_length=10, verbose_name='Document Record Date: '),
        ),
        migrations.AlterField(
            model_name='documentinfomodel',
            name='document_image',
            field=models.ImageField(blank=True, default='', upload_to='document_image/', verbose_name='Documnet Image or Scan'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_date',
            field=models.DateTimeField(default=document_panel.models.get_time, max_length=20, verbose_name='Liability Day'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_desc',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Liability Description: '),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_lastday',
            field=models.DateTimeField(blank=True, default=document_panel.models.get_time, max_length=20, verbose_name='Liability Last day'),
        ),
        migrations.AlterField(
            model_name='liabilityinfomodel',
            name='liability_return',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Liability Return day'),
        ),
    ]
