# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import operation_panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.DateTimeField(default=operation_panel.models.get_time)),
                ('in_or_out', models.BooleanField(max_length=1, verbose_name='In or Out: ')),
                ('company_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DateField(default=operation_panel.models.get_date, verbose_name='leave Start: ')),
                ('end', models.DateField(default=operation_panel.models.get_date, verbose_name='leave End: ')),
                ('reason', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='leave Reason: ')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student_leave',
            },
        ),
    ]
