# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import operation_panel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('time', models.DateTimeField(default=operation_panel.models.get_time)),
                ('in_or_out', models.BooleanField(max_length=1)),
                ('company_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CityInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_slug', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'adres_city',
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20)),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('neighborhood_slug', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adres_neigh',
            },
        ),
        migrations.CreateModel(
            name='PostalCodeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=20)),
                ('pk_name', models.CharField(max_length=100)),
                ('pk_slug', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'adres_postal',
            },
        ),
        migrations.CreateModel(
            name='StudentLeaveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('start', models.DateField(default=operation_panel.models.get_date, verbose_name='leave Start: ')),
                ('end', models.DateField(default=operation_panel.models.get_date, verbose_name='leave End: ')),
                ('reason', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='leave Reason: ')),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student_leave',
            },
        ),
        migrations.CreateModel(
            name='TownInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('town_name', models.CharField(max_length=50)),
                ('town_slug', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'adres_town',
            },
        ),
    ]
