# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(blank=True, max_length=10, null=True)),
                ('traffic_date', models.DateField(default=datetime.date.today)),
                ('in_or_out', models.CharField(max_length=1, verbose_name='In or Out: ')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLeaveModel',
            fields=[
                ('leave_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='leave_id: ')),
                ('person_id', models.CharField(blank=True, max_length=10, null=True)),
                ('leave_start', models.DateField(default='2017-07-02', verbose_name='leave Start: ')),
                ('leave_end', models.DateField(default='2017-07-05', verbose_name='leave End: ')),
                ('leave_reason', models.CharField(blank=True, max_length=100, verbose_name='leave Reason: ')),
            ],
            options={
                'db_table': 'student_leave',
            },
        ),
    ]
