# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='person_id',
            field=models.ForeignKey(default='1701001', on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Person: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='person_id',
            field=models.ForeignKey(default='1701001', on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Permitted Person: '),
            preserve_default=False,
        ),
    ]
