# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='person',
            field=models.ForeignKey(default='1701002', on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Person: '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='person',
            field=models.ForeignKey(default='1701002', on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Permitted Person: '),
            preserve_default=False,
        ),
    ]
