# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='neighborhoodinfomodel',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_panel.TownInfoModel'),
        ),
        migrations.AlterField(
            model_name='postalcodeinfomodel',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_panel.NeighborhoodInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Permitted Person: '),
        ),
        migrations.AlterField(
            model_name='towninfomodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_panel.CityInfoModel'),
        ),
    ]
