# Generated by Django 2.0.1 on 2018-01-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='notificationinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='vacationinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='vacationinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonalInfoModel'),
        ),
    ]
