# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0002_auto_20170711_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentleavemodel',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='studentleavemodel',
            name='id',
            field=models.AutoField(auto_created=True, default='1741001', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
