# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import operation_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0003_auto_20170711_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='traffic_date',
            field=models.DateTimeField(default=operation_panel.models.get_time),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='leave_end',
            field=models.DateTimeField(default='2017-07-05', verbose_name='leave End: '),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='leave_start',
            field=models.DateTimeField(default=operation_panel.models.get_time, verbose_name='leave Start: '),
        ),
    ]
