# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0003_auto_20171003_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='person',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='person',
            field=models.CharField(max_length=10),
        ),
    ]
