# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import operation_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0004_auto_20170721_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='traffic_date',
            field=models.DateField(default=operation_panel.models.get_time),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='leave_end',
            field=models.DateField(default=operation_panel.models.get_date, verbose_name='leave End: '),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='leave_reason',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='leave Reason: '),
        ),
        migrations.AlterField(
            model_name='studentleavemodel',
            name='leave_start',
            field=models.DateField(default=operation_panel.models.get_date, verbose_name='leave Start: '),
        ),
    ]
