# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import operation_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0005_auto_20170801_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='traffic_date',
            field=models.DateTimeField(default=operation_panel.models.get_time),
        ),
    ]
