# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0005_auto_20171003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='in_or_out',
            field=models.BooleanField(max_length=1),
        ),
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
    ]
