# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0006_auto_20171018_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_slug', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'adres_city',
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('neighborhood_slug', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adres_neigh',
            },
        ),
        migrations.CreateModel(
            name='PostalCodeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_name', models.CharField(max_length=100)),
                ('pk_slug', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=30)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_panel.NeighborhoodInfoModel')),
            ],
            options={
                'db_table': 'adres_postal',
            },
        ),
        migrations.CreateModel(
            name='TownInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=50)),
                ('town_slug', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_panel.CityInfoModel')),
            ],
            options={
                'db_table': 'adres_town',
            },
        ),
        migrations.AddField(
            model_name='neighborhoodinfomodel',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation_panel.TownInfoModel'),
        ),
    ]
