# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_panel', '0006_auto_20170801_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfomodel',
            name='in_or_out',
            field=models.BooleanField(max_length=1, verbose_name='In or Out: '),
        ),
    ]
