# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureInfoModel',
            fields=[
                ('fixture_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=5)),
                ('fixture_type', models.CharField(choices=[(b'1', b'Box Spring'), (b'2', b'Bed'), (b'3', b'Wardrobe'), (b'4', b'Carpet'), (b'5', b'Night Stand'), (b'6', b'Tulle'), (b'7', b'Veil'), (b'8', b'Table'), (b'9', b'Chair'), (b'10', b'Coat Hanger'), (b'11', b'Bookcase'), (b'12', b'Lamp'), (b'13', b'Klima'), (b'14', b'Mirror')], max_length=20)),
                ('fixture_notes', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fixture_info',
            },
        ),
        migrations.CreateModel(
            name='RoomInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('room_floor', models.CharField(max_length=20)),
                ('room_people', models.CharField(choices=[(b'1', b'One Person'), (b'2', b'Two People'), (b'3', b'Three People'), (b'4', b'Four People'), (b'5', b'Five People')], max_length=20)),
                ('room_type', models.CharField(choices=[(b'1', b'With Shower'), (b'2', b'Double-Decker'), (b'3', b'Normal'), (b'4', b'Kitchen')], max_length=20)),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
    ]
