# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixturepanel', '0002_roominfomodel_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureinfomodel',
            name='fixture_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'fixture_image/'),
        ),
        migrations.AlterField(
            model_name='roominfomodel',
            name='room_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'room_image/'),
        ),
    ]
