# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInfoModel',
            fields=[
                ('id', models.CharField(help_text=b'Parent Id', max_length=50, primary_key=True, serialize=False, verbose_name=b'Parent Id: ')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.CharField(help_text=b'Parent Name', max_length=20, verbose_name=b'Parent Name')),
                ('parent_lastname', models.CharField(max_length=20, verbose_name=b'Parent Lastname')),
                ('parent_TCN', models.CharField(blank=True, max_length=11, verbose_name=b'Parent TCN')),
                ('parent_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name=b'Parent Phone')),
                ('parent_email', models.EmailField(max_length=254, verbose_name=b'Parent E-mail')),
                ('relative_degree', models.CharField(default=b'Father', max_length=20, verbose_name=b'Relative Degree')),
                ('parent_job', models.CharField(blank=True, max_length=20, verbose_name=b'Parent Job')),
            ],
            options={
                'db_table': 'parent_info',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfoModel',
            fields=[
                ('id', models.CharField(help_text=b'ID', max_length=7, primary_key=True, serialize=False, verbose_name=b'Personal Id')),
                ('personal_tcn', models.CharField(default=b'00000000000', help_text=b'11 digit', max_length=11, unique=True, verbose_name=b'TC No')),
                ('personal_name', models.CharField(default=b'Ahmet', help_text=b'Personal Name', max_length=200, verbose_name=b'Personal Name')),
                ('personal_lastname', models.CharField(default=b'Yilmaz', help_text=b'Personal Last Name', max_length=200, verbose_name=b'Personal Last Name')),
                ('personal_phone', phonenumber_field.modelfields.PhoneNumberField(default=b'+905553332211', help_text=b'+905553332211', max_length=128, verbose_name=b'Phone Number')),
                ('personal_email', models.EmailField(default=b'qwe@gam.com', help_text=b'aaaaa@aaaa.aaa', max_length=254, unique=True, verbose_name=b'Personal Email')),
                ('personal_startday', models.DateField(default=datetime.date.today, help_text=b'1990-12-31', verbose_name=b'Start Day')),
                ('personal_endday', models.DateField(blank=True, help_text=b'1990-12-31', null=True, verbose_name=b'Quit Day')),
                ('personal_city', models.CharField(choices=[('01', 'Adana'), ('02', 'Ad\u0131yaman'), ('03', 'Afyonkarahisar'), ('04', 'A\u011fr\u0131'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Ayd\u0131n'), ('10', 'Bal\u0131kesir'), ('74', 'Bart\u0131n'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bing\xf6l'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', '\xc7anakkale'), ('18', '\xc7ank\u0131r\u0131'), ('19', '\xc7orum'), ('20', 'Denizli'), ('21', 'Diyarbak\u0131r'), ('81', 'D\xfczce'), ('22', 'Edirne'), ('23', 'Elaz\u0131\u011f'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eski\u015fehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'G\xfcm\xfc\u015fhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'I\u011fd\u0131r'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', '\u0130stanbul'), ('35', '\u0130zmir'), ('78', 'Karab\xfck'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'K\u0131rklareli'), ('40', 'K\u0131r\u015fehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'K\xfctahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmara\u015f'), ('70', 'Karaman'), ('71', 'K\u0131r\u0131kkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Mu\u011fla'), ('49', 'Mu\u015f'), ('50', 'Nev\u015fehir'), ('51', 'Ni\u011fde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', '\u015e\u0131rnak'), ('59', 'Tekirda\u011f'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', '\u015eanl\u0131urfa'), ('64', 'U\u015fak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default=b'Ankara', help_text=b'City Where Personal From', max_length=20, null=True, verbose_name=b'Personal City')),
                ('personal_town', models.CharField(default=b'yok', help_text=b'Town Where Personal From', max_length=20, null=True, verbose_name=b'Personal Town')),
                ('personal_adress', models.CharField(default=b'yok', help_text=b'Distinct, Street, Building No, Flat No', max_length=50, null=True, verbose_name=b'Personal Address')),
                ('personal_birthday', models.DateField(default=b'1990-12-31', help_text=b'1990-12-31', verbose_name=b'Birthday')),
                ('blood_type', models.CharField(choices=[(b'0', b'0 rh +'), (b'1', b'0 rh -'), (b'2', b'A rh +'), (b'3', b'A rh -'), (b'4', b'B rh +'), (b'5', b'B rh -'), (b'6', b'AB rh+'), (b'7', b'AB rh-')], default=b'0 rh +', help_text=b'Blood Type', max_length=20, null=True, verbose_name=b'Blood Type')),
                ('health_notes', models.CharField(blank=True, default=b'-', help_text=b'Health Notes', max_length=100, null=True, verbose_name=b'Health Notes')),
                ('special_notes', models.CharField(blank=True, default=b'-', help_text=b'Special Notes', max_length=100, null=True, verbose_name=b'Special Notes')),
                ('image_field', models.ImageField(blank=True, default=b'Desktop/asd.jpg', help_text=b'Profile Image Path', null=True, upload_to=b'profile_pic/', verbose_name=b'Image Upload')),
            ],
            options={
                'db_table': 'personal_info',
            },
        ),
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.CharField(help_text=b'ID', max_length=7, primary_key=True, serialize=False, verbose_name=b'Student Id')),
                ('student_position', models.BooleanField(help_text=b'In-Out', verbose_name=b'Student Position')),
                ('student_tcn', models.CharField(default=b'00000000000', help_text=b'11 digit', max_length=11, unique=True, verbose_name=b'TC No')),
                ('student_name', models.CharField(default=b'Ahmet', help_text=b'Student Name', max_length=200, verbose_name=b'Student Name')),
                ('student_lastname', models.CharField(default=b'Yilmaz', help_text=b'Student Last Name', max_length=200, verbose_name=b'Student Last Name')),
                ('student_phone', phonenumber_field.modelfields.PhoneNumberField(default=b'+905553332211', help_text=b'+905553332211', max_length=128, verbose_name=b'Phone Number')),
                ('student_email', models.EmailField(default=b'qwe@gam.com', help_text=b'aaaaa@aaaa.aaa', max_length=254, unique=True, verbose_name=b'Student Email')),
                ('student_birthday', models.DateField(default=b'1990-12-31', help_text=b'1990-12-31', verbose_name=b'Birthday')),
                ('student_regday', models.DateField(default=datetime.date.today, help_text=b'1990-12-31', verbose_name=b'Registration Day')),
                ('student_city', models.CharField(choices=[('01', 'Adana'), ('02', 'Ad\u0131yaman'), ('03', 'Afyonkarahisar'), ('04', 'A\u011fr\u0131'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Ayd\u0131n'), ('10', 'Bal\u0131kesir'), ('74', 'Bart\u0131n'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bing\xf6l'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', '\xc7anakkale'), ('18', '\xc7ank\u0131r\u0131'), ('19', '\xc7orum'), ('20', 'Denizli'), ('21', 'Diyarbak\u0131r'), ('81', 'D\xfczce'), ('22', 'Edirne'), ('23', 'Elaz\u0131\u011f'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eski\u015fehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'G\xfcm\xfc\u015fhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'I\u011fd\u0131r'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', '\u0130stanbul'), ('35', '\u0130zmir'), ('78', 'Karab\xfck'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'K\u0131rklareli'), ('40', 'K\u0131r\u015fehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'K\xfctahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmara\u015f'), ('70', 'Karaman'), ('71', 'K\u0131r\u0131kkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Mu\u011fla'), ('49', 'Mu\u015f'), ('50', 'Nev\u015fehir'), ('51', 'Ni\u011fde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', '\u015e\u0131rnak'), ('59', 'Tekirda\u011f'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', '\u015eanl\u0131urfa'), ('64', 'U\u015fak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default=b'Ankara', help_text=b'City Where Student From', max_length=20, null=True, verbose_name=b'Student City')),
                ('student_town', models.CharField(default=b'yok', help_text=b'Town Where Student From', max_length=20, null=True, verbose_name=b'Student Town')),
                ('student_adress', models.CharField(default=b'yok', help_text=b'Distinct, Street, Building No, Flat No', max_length=50, null=True, verbose_name=b'Student Address')),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('student_type', models.CharField(choices=[(b'0', b'Guest'), (b'1', b'Temporary'), (b'2', b'Permanent')], default=b'Permanent', help_text=b'Student Accommodation Type', max_length=10, verbose_name=b'Student Type')),
                ('birth_place', models.CharField(choices=[('01', 'Adana'), ('02', 'Ad\u0131yaman'), ('03', 'Afyonkarahisar'), ('04', 'A\u011fr\u0131'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Ayd\u0131n'), ('10', 'Bal\u0131kesir'), ('74', 'Bart\u0131n'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bing\xf6l'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', '\xc7anakkale'), ('18', '\xc7ank\u0131r\u0131'), ('19', '\xc7orum'), ('20', 'Denizli'), ('21', 'Diyarbak\u0131r'), ('81', 'D\xfczce'), ('22', 'Edirne'), ('23', 'Elaz\u0131\u011f'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eski\u015fehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'G\xfcm\xfc\u015fhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'I\u011fd\u0131r'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', '\u0130stanbul'), ('35', '\u0130zmir'), ('78', 'Karab\xfck'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'K\u0131rklareli'), ('40', 'K\u0131r\u015fehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'K\xfctahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmara\u015f'), ('70', 'Karaman'), ('71', 'K\u0131r\u0131kkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Mu\u011fla'), ('49', 'Mu\u015f'), ('50', 'Nev\u015fehir'), ('51', 'Ni\u011fde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', '\u015e\u0131rnak'), ('59', 'Tekirda\u011f'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', '\u015eanl\u0131urfa'), ('64', 'U\u015fak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default=('01', 'Adana'), help_text=b'City Where Student Birth', max_length=20, null=True, verbose_name=b'Birth City')),
                ('school_name', models.CharField(default=b'okulsuz', help_text=b'School Name', max_length=50, null=True, verbose_name=b'School Name')),
                ('education_year', models.CharField(choices=[(b'0', b'Preparation'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6')], default=(b'0', b'Preparation'), help_text=b'Education Year', max_length=20, null=True, verbose_name=b'Education Year')),
                ('blood_type', models.CharField(choices=[(b'0', b'0 rh +'), (b'1', b'0 rh -'), (b'2', b'A rh +'), (b'3', b'A rh -'), (b'4', b'B rh +'), (b'5', b'B rh -'), (b'6', b'AB rh+'), (b'7', b'AB rh-')], default=b'0 rh +', help_text=b'Blood Type', max_length=20, null=True, verbose_name=b'Blood Type')),
                ('health_notes', models.CharField(blank=True, default=b'-', help_text=b'Health Notes', max_length=100, null=True, verbose_name=b'Health Notes')),
                ('special_notes', models.CharField(blank=True, default=b'-', help_text=b'Special Notes', max_length=100, null=True, verbose_name=b'Special Notes')),
                ('file_field', models.ImageField(blank=True, default=b'Desktop/asd.jpg', help_text=b'Add an Image', null=True, upload_to=b'profile_pic/', verbose_name=b'Image Upload')),
            ],
            options={
                'db_table': 'student_info',
            },
        ),
    ]
