# Generated by Django 2.0.1 on 2018-01-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_id',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel'),
        ),
    ]
