# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.ForeignKey(default='1701001', on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_no',
            field=models.ForeignKey(help_text=b'Room Number Student Assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name=b'Room Number'),
        ),
    ]
