# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0002_auto_20171030_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='salary',
            field=models.CharField(default='2000.0', max_length=7),
        ),
    ]
