# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0002_auto_20170711_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_gender',
            field=models.CharField(blank='True', choices=[('1', 'Kadın'), ('2', 'Erkek')], default='1', max_length=50, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_idcard_type',
            field=models.CharField(blank='True', choices=[('1', 'Nüfus Cüzdanı'), ('2', 'TC Kimliği'), ('3', 'Ehliyet'), ('4', 'Pasaport'), ('5', 'Diğer')], default='1', max_length=50, verbose_name='Kimlik Türü'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_medeni_hali',
            field=models.CharField(blank='True', choices=[('1', 'Bekar'), ('2', 'Evli'), ('3', 'Dul'), ('4', 'Diğer')], default='1', max_length=50, verbose_name='Medeni Hali'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_nufus_ailesira',
            field=models.CharField(blank='True', default='00001', max_length=50, verbose_name='Aile Sira No'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_nufus_cilt',
            field=models.CharField(blank='True', default='0001', max_length=50, verbose_name='Cilt No'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_nufus_sirano',
            field=models.CharField(blank='True', default='0001', max_length=50, verbose_name='Sira No'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_register_distinct',
            field=models.CharField(blank='True', default='olabilir', max_length=50, verbose_name='Kayıtlı Olduğu Mahalle'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_register_town',
            field=models.CharField(blank='True', default='yok', max_length=50, verbose_name='Kayıtlı Olduğu İlçe'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='s_register_vilage',
            field=models.CharField(blank='True', choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=50, verbose_name='Kayıtlı Olduğu İl'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='student_father',
            field=models.CharField(default='Mehmet', max_length=50, verbose_name='Baba Adı'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='student_mother',
            field=models.CharField(default='Ayse', max_length=50, verbose_name='Anne Adı'),
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='student_nation',
            field=models.CharField(blank='True', choices=[('1', 'Türkiye')], default='1', max_length=50, verbose_name='Uyruk'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='id',
            field=models.CharField(help_text='Parent Id', max_length=50, primary_key=True, serialize=False, verbose_name='Veli No'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_TCN',
            field=models.CharField(blank=True, max_length=11, verbose_name='Veli TCN'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_email',
            field=models.EmailField(max_length=254, verbose_name='Veli Email Adresi'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_job',
            field=models.CharField(blank=True, max_length=20, verbose_name='Veli Mesleği'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_lastname',
            field=models.CharField(max_length=20, verbose_name='Veli Soyadı'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_name',
            field=models.CharField(help_text='Parent Name', max_length=20, verbose_name='Veli Adı'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Veli Telefonu'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='relative_degree',
            field=models.CharField(default='Father', max_length=20, verbose_name='Yakınlık Derecesi'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Öğrenci No'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='blood_type',
            field=models.CharField(choices=[('0', '0 rh +'), ('1', '0 rh -'), ('2', 'A rh +'), ('3', 'A rh -'), ('4', 'B rh +'), ('5', 'B rh -'), ('6', 'AB rh+'), ('7', 'AB rh-')], default='0 rh +', help_text='Blood Type', max_length=20, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='health_notes',
            field=models.CharField(blank=True, default='-', help_text='Health Notes', max_length=100, null=True, verbose_name='Sağlık Notları'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='id',
            field=models.CharField(help_text='ID', max_length=7, primary_key=True, serialize=False, verbose_name='Personel No'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='image_field',
            field=models.ImageField(blank=True, default='Desktop/asd.jpg', help_text='Profile Image Path', null=True, upload_to='profile_pic/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_adress',
            field=models.CharField(default='yok', help_text='Distinct, Street, Building No, Flat No', max_length=50, null=True, verbose_name='Personel Adres'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_birthday',
            field=models.DateField(default='1990-12-31', help_text='1990-12-31', verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_city',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='Ankara', help_text='City Where Personal From', max_length=20, null=True, verbose_name='Personel Adres İli'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_email',
            field=models.EmailField(default='qwe@gam.com', help_text='aaaaa@aaaa.aaa', max_length=254, unique=True, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_endday',
            field=models.DateField(blank=True, help_text='1990-12-31', null=True, verbose_name='İşten Ayrılma Günü'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_lastname',
            field=models.CharField(default='Yilmaz', help_text='Personal Last Name', max_length=200, verbose_name='Personel Soyismi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_name',
            field=models.CharField(default='Ahmet', help_text='Personal Name', max_length=200, verbose_name='Personel İsmi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905553332211', help_text='+905553332211', max_length=128, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_startday',
            field=models.DateField(default=datetime.date.today, help_text='1990-12-31', verbose_name='İşe Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_tcn',
            field=models.CharField(default='00000000000', help_text='11 digit', max_length=11, unique=True, verbose_name='Personel TC No'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_town',
            field=models.CharField(default='yok', help_text='Town Where Personal From', max_length=20, null=True, verbose_name='Personel Adres İlçesi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='special_notes',
            field=models.CharField(blank=True, default='-', help_text='Special Notes', max_length=100, null=True, verbose_name='Özel Notlar'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='birth_place',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default=('01', 'Adana'), help_text='City Where Student Birth', max_length=20, null=True, verbose_name='Birth City'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='blood_type',
            field=models.CharField(choices=[('0', '0 rh +'), ('1', '0 rh -'), ('2', 'A rh +'), ('3', 'A rh -'), ('4', 'B rh +'), ('5', 'B rh -'), ('6', 'AB rh+'), ('7', 'AB rh-')], default='0 rh +', help_text='Blood Type', max_length=20, null=True, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='education_year',
            field=models.CharField(choices=[('0', 'Preparation'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=('0', 'Preparation'), help_text='Education Year', max_length=20, null=True, verbose_name='Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='file_field',
            field=models.ImageField(blank=True, default='Desktop/asd.jpg', help_text='Add an Image', null=True, upload_to='profile_pic/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='health_notes',
            field=models.CharField(blank=True, default='-', help_text='Health Notes', max_length=100, null=True, verbose_name='Sağlık Notları'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='id',
            field=models.CharField(help_text='ID', max_length=7, primary_key=True, serialize=False, verbose_name='Öğrencinin No'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_no',
            field=models.ForeignKey(help_text='Room Number Student Assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name='Oda Numarası'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='school_name',
            field=models.CharField(default='okulsuz', help_text='School Name', max_length=50, null=True, verbose_name='Okul'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='special_notes',
            field=models.CharField(blank=True, default='-', help_text='Special Notes', max_length=100, null=True, verbose_name='Özel Notlar'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_adress',
            field=models.CharField(default='yok', help_text='Distinct, Street, Building No, Flat No', max_length=50, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_birthday',
            field=models.DateField(default='1990-12-31', help_text='1990-12-31', verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_city',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='Ankara', help_text='City Where Student From', max_length=20, null=True, verbose_name='Adres Şehri'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_email',
            field=models.EmailField(default='qwe@gam.com', help_text='aaaaa@aaaa.aaa', max_length=254, unique=True, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_lastname',
            field=models.CharField(default='Yilmaz', help_text='Student Last Name', max_length=50, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_name',
            field=models.CharField(default='Ahmet', help_text='Student Name', max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905553332211', help_text='+905553332211', max_length=128, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_position',
            field=models.BooleanField(default=True, help_text='In-Out', verbose_name='Öğrenci Konumu'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_regday',
            field=models.DateField(default=datetime.date.today, help_text='1990-12-31', verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_tcn',
            field=models.CharField(default='00000000000', help_text='11 digit', max_length=11, unique=True, verbose_name='TC No'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_town',
            field=models.CharField(default='yok', help_text='Town Where Student From', max_length=20, null=True, verbose_name='Adres İlçesi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_type',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Geçici'), ('2', 'Misafir')], default='Permanent', help_text='Student Accommodation Type', max_length=10, verbose_name='Öğrenci Türü'),
        ),
    ]
