# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0003_auto_20170714_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIDInfoModel',
            fields=[
                ('s_tcn', models.CharField(default='00000000000', help_text='11 digit', max_length=11, primary_key=True, serialize=False, verbose_name='TC No')),
                ('s_name', models.CharField(default='Ahmet', help_text='Student Name', max_length=50, verbose_name='İsim')),
                ('s_lastname', models.CharField(default='Yilmaz', help_text='Student Last Name', max_length=50, verbose_name='Soyisim')),
                ('s_birthday', models.DateField(default='1990-12-31', help_text='1990-12-31', verbose_name='Doğum Tarihi')),
                ('s_birth_place', models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default=('01', 'Adana'), help_text='City Where Student Birth', max_length=20, null=True, verbose_name='Birth City')),
                ('s_father', models.CharField(default='Mehmet', max_length=50, verbose_name='Baba Adı')),
                ('s_mother', models.CharField(default='Ayse', max_length=50, verbose_name='Anne Adı')),
                ('s_nation', models.CharField(blank='True', choices=[('1', 'Türkiye')], default='1', max_length=50, verbose_name='Uyruk')),
                ('s_idcard_type', models.CharField(blank='True', choices=[('1', 'Nüfus Cüzdanı'), ('2', 'TC Kimliği'), ('3', 'Ehliyet'), ('4', 'Pasaport'), ('5', 'Diğer')], default='1', max_length=50, verbose_name='Kimlik Türü')),
                ('s_register_vilage', models.CharField(blank='True', choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=50, verbose_name='Kayıtlı Olduğu İl')),
                ('s_register_town', models.CharField(blank='True', default='yok', max_length=50, verbose_name='Kayıtlı Olduğu İlçe')),
                ('s_register_distinct', models.CharField(blank='True', default='olabilir', max_length=50, verbose_name='Kayıtlı Olduğu Mahalle')),
                ('s_gender', models.CharField(blank='True', choices=[('1', 'Kadın'), ('2', 'Erkek')], default='1', max_length=50, verbose_name='Cinsiyet')),
                ('s_nufus_cilt', models.CharField(blank='True', default='0001', max_length=50, verbose_name='Cilt No')),
                ('s_nufus_ailesira', models.CharField(blank='True', default='00001', max_length=50, verbose_name='Aile Sira No')),
                ('s_nufus_sirano', models.CharField(blank='True', default='0001', max_length=50, verbose_name='Sira No')),
                ('s_medeni_hali', models.CharField(blank='True', choices=[('1', 'Bekar'), ('2', 'Evli'), ('3', 'Dul'), ('4', 'Diğer')], default='1', max_length=50, verbose_name='Medeni Hali')),
            ],
            options={
                'db_table': 'personid_info',
            },
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_gender',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_idcard_type',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_medeni_hali',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_nufus_ailesira',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_nufus_cilt',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_nufus_sirano',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_register_distinct',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_register_town',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='s_register_vilage',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_birthday',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_father',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_lastname',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_mother',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='studentinfomodel',
            name='student_nation',
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='id',
            field=models.CharField(help_text='ID', max_length=7, primary_key=True, serialize=False, verbose_name='Öğrenci No'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_tcn',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
