# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0003_auto_20171003_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='person',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='tcn',
            field=models.CharField(help_text='11 digit', max_length=11, unique=True, verbose_name='Personel TC No'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='tcn',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
