# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0004_auto_20171003_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Öğrenci No'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel', verbose_name='Personelin Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='company_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_panel.CompanyInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_id',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name='Oda Numarası'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel', verbose_name='Öğrencinin Kimlik Numarası'),
        ),
    ]
