# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import person_panel.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0005_auto_20171003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfomodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='id',
            field=models.CharField(default='1704001', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='relative_degree',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='tcn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='blood_type',
            field=models.CharField(choices=[('0', '0 rh +'), ('1', '0 rh -'), ('2', 'A rh +'), ('3', 'A rh -'), ('4', 'B rh +'), ('5', 'B rh -'), ('6', 'AB rh+'), ('7', 'AB rh-')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='city',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='end_day',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='health_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='id',
            field=models.CharField(default='', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='image_field',
            field=models.ImageField(default='', upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905553332211', max_length=13),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='special_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='start_day',
            field=models.DateField(default=person_panel.models.get_date, max_length=10),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='birth_day',
            field=models.DateField(default='1990-12-31', max_length=10),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='birth_place',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='father',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='gender',
            field=models.CharField(choices=[('1', 'Kadın'), ('2', 'Erkek')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='idcard_type',
            field=models.CharField(choices=[('1', 'Nüfus Cüzdanı'), ('2', 'TC Kimliği'), ('3', 'Ehliyet'), ('4', 'Pasaport'), ('5', 'Diğer')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='medeni_hali',
            field=models.CharField(choices=[('1', 'Bekar'), ('2', 'Evli'), ('3', 'Dul'), ('4', 'Diğer')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='mother',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='nation',
            field=models.CharField(choices=[('1', 'Türkiye')], default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='nufus_ailesira',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='nufus_cilt',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='nufus_sirano',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='register_distinct',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='register_town',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='register_vilage',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='tcn',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='blood_type',
            field=models.CharField(choices=[('0', '0 rh +'), ('1', '0 rh -'), ('2', 'A rh +'), ('3', 'A rh -'), ('4', 'B rh +'), ('5', 'B rh -'), ('6', 'AB rh+'), ('7', 'AB rh-')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='city',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='education_year',
            field=models.CharField(choices=[('0', 'Preparation'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='health_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='id',
            field=models.CharField(default='1701001', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='image_field',
            field=models.ImageField(default='', upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905553332211', max_length=13),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='position',
            field=models.BooleanField(default='1'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_id',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='school_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='special_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='start_day',
            field=models.DateField(default=person_panel.models.get_date, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='town',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='type',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Geçici'), ('2', 'Misafir')], default='1', max_length=10),
        ),
    ]
