# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import person_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0006_auto_20170715_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_birthday',
            field=models.DateTimeField(default='31-12-1991', help_text='1990-12-31', verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_endday',
            field=models.DateTimeField(blank=True, help_text='1990-12-31', null=True, verbose_name='İşten Ayrılma Günü'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_startday',
            field=models.DateTimeField(default=person_panel.models.get_time, help_text='1990-12-31', verbose_name='İşe Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_birthday',
            field=models.DateTimeField(default='1990-12-31', help_text='1990-12-31', verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_regday',
            field=models.DateTimeField(default=person_panel.models.get_time, help_text='1990-12-31', verbose_name='Kayıt Tarihi'),
        ),
    ]
