# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import person_panel.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0007_auto_20170721_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfomodel',
            name='personal_birthday',
        ),
        migrations.RemoveField(
            model_name='personalinfomodel',
            name='personal_lastname',
        ),
        migrations.RemoveField(
            model_name='personalinfomodel',
            name='personal_name',
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Veli No'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_TCN',
            field=models.CharField(default='', max_length=11, verbose_name='Veli TCN'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Veli Email Adresi'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_job',
            field=models.CharField(default='', max_length=20, verbose_name='Veli Mesleği'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_lastname',
            field=models.CharField(default='', max_length=20, verbose_name='Veli Soyadı'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_name',
            field=models.CharField(default='', max_length=20, verbose_name='Veli Adı'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Veli Telefonu'),
        ),
        migrations.AlterField(
            model_name='parentinfomodel',
            name='relative_degree',
            field=models.CharField(default='', max_length=20, verbose_name='Yakınlık Derecesi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='blood_type',
            field=models.CharField(choices=[('0', '0 rh +'), ('1', '0 rh -'), ('2', 'A rh +'), ('3', 'A rh -'), ('4', 'B rh +'), ('5', 'B rh -'), ('6', 'AB rh+'), ('7', 'AB rh-')], default='1', max_length=20, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='health_notes',
            field=models.CharField(default='', max_length=200, verbose_name='Sağlık Notları'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='image_field',
            field=models.ImageField(default='', upload_to='profile_pic/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_adress',
            field=models.CharField(default='', max_length=100, verbose_name='Personel Adres'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_city',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=20, verbose_name='Personel Adres İli'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_endday',
            field=models.DateTimeField(default=person_panel.models.get_time, verbose_name='İşten Ayrılma Günü'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905553332211', max_length=13, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_startday',
            field=models.DateTimeField(default=person_panel.models.get_time, verbose_name='İşe Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_tcn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_panel.PersonIDInfoModel', verbose_name='Personelin Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_town',
            field=models.CharField(default='', max_length=20, verbose_name='Personel Adres İlçesi'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='special_notes',
            field=models.CharField(default='', max_length=200, verbose_name='Özel Notlar'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_birth_place',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=20, null=True, verbose_name='Doğduğu Şehir'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_birthday',
            field=models.DateTimeField(default='1990-12-31 00:00:00', verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_father',
            field=models.CharField(default='', max_length=50, verbose_name='Baba Adı'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_gender',
            field=models.CharField(choices=[('1', 'Kadın'), ('2', 'Erkek')], default='1', max_length=5, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_idcard_type',
            field=models.CharField(choices=[('1', 'Nüfus Cüzdanı'), ('2', 'TC Kimliği'), ('3', 'Ehliyet'), ('4', 'Pasaport'), ('5', 'Diğer')], default='1', max_length=50, verbose_name='Kimlik Türü'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_lastname',
            field=models.CharField(default='Yilmaz', max_length=50, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_medeni_hali',
            field=models.CharField(choices=[('1', 'Bekar'), ('2', 'Evli'), ('3', 'Dul'), ('4', 'Diğer')], default='1', max_length=10, verbose_name='Medeni Hali'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_mother',
            field=models.CharField(default='', max_length=50, verbose_name='Anne Adı'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_name',
            field=models.CharField(default='Ahmet', max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_nation',
            field=models.CharField(choices=[('1', 'Türkiye')], default='1', max_length=50, verbose_name='Uyruk'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_nufus_ailesira',
            field=models.CharField(default='', max_length=5, verbose_name='Aile Sira No'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_nufus_cilt',
            field=models.CharField(default='', max_length=4, verbose_name='Cilt No'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_nufus_sirano',
            field=models.CharField(default='', max_length=4, verbose_name='Sira No'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_register_distinct',
            field=models.CharField(default='', max_length=50, verbose_name='Kayıtlı Olduğu Mahalle'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_register_town',
            field=models.CharField(default='', max_length=50, verbose_name='Kayıtlı Olduğu İlçe'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_register_vilage',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=50, verbose_name='Kayıtlı Olduğu İl'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_tcn',
            field=models.CharField(default='00000000000', max_length=11, primary_key=True, serialize=False, verbose_name='TC No'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='blood_type',
            field=models.CharField(choices=[('0', '0 rh +'), ('1', '0 rh -'), ('2', 'A rh +'), ('3', 'A rh -'), ('4', 'B rh +'), ('5', 'B rh -'), ('6', 'AB rh+'), ('7', 'AB rh-')], default='1', max_length=20, verbose_name='Kan Grubu'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='education_year',
            field=models.CharField(choices=[('0', 'Preparation'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20, verbose_name='Eğitim Yılı'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='file_field',
            field=models.ImageField(default='', upload_to='profile_pic/', verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='health_notes',
            field=models.CharField(default='', max_length=200, verbose_name='Sağlık Notları'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='room_no',
            field=models.ForeignKey(default='101', on_delete=django.db.models.deletion.CASCADE, to='stock_panel.RoomInfoModel', verbose_name='Oda Numarası'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='school_name',
            field=models.CharField(default='', max_length=50, verbose_name='Okul'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='special_notes',
            field=models.CharField(default='', max_length=200, verbose_name='Özel Notlar'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_adress',
            field=models.CharField(default='', max_length=100, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_city',
            field=models.CharField(choices=[('01', 'Adana'), ('02', 'Adıyaman'), ('03', 'Afyonkarahisar'), ('04', 'Ağrı'), ('68', 'Aksaray'), ('05', 'Amasya'), ('06', 'Ankara'), ('07', 'Antalya'), ('75', 'Ardahan'), ('08', 'Artvin'), ('09', 'Aydın'), ('10', 'Balıkesir'), ('74', 'Bartın'), ('72', 'Batman'), ('69', 'Bayburt'), ('11', 'Bilecik'), ('12', 'Bingöl'), ('13', 'Bitlis'), ('14', 'Bolu'), ('15', 'Burdur'), ('16', 'Bursa'), ('17', 'Çanakkale'), ('18', 'Çankırı'), ('19', 'Çorum'), ('20', 'Denizli'), ('21', 'Diyarbakır'), ('81', 'Düzce'), ('22', 'Edirne'), ('23', 'Elazığ'), ('24', 'Erzincan'), ('25', 'Erzurum'), ('26', 'Eskişehir'), ('27', 'Gaziantep'), ('28', 'Giresun'), ('29', 'Gümüşhane'), ('30', 'Hakkari'), ('31', 'Hatay'), ('76', 'Iğdır'), ('32', 'Isparta'), ('33', 'Mersin'), ('34', 'İstanbul'), ('35', 'İzmir'), ('78', 'Karabük'), ('36', 'Kars'), ('37', 'Kastamonu'), ('38', 'Kayseri'), ('39', 'Kırklareli'), ('40', 'Kırşehir'), ('41', 'Kocaeli'), ('42', 'Konya'), ('43', 'Kütahya'), ('44', 'Malatya'), ('45', 'Manisa'), ('46', 'Kahramanmaraş'), ('70', 'Karaman'), ('71', 'Kırıkkale'), ('79', 'Kilis'), ('47', 'Mardin'), ('48', 'Muğla'), ('49', 'Muş'), ('50', 'Nevşehir'), ('51', 'Niğde'), ('52', 'Ordu'), ('80', 'Osmaniye'), ('53', 'Rize'), ('54', 'Sakarya'), ('55', 'Samsun'), ('56', 'Siirt'), ('57', 'Sinop'), ('58', 'Sivas'), ('73', 'Şırnak'), ('59', 'Tekirdağ'), ('60', 'Tokat'), ('61', 'Trabzon'), ('62', 'Tunceli'), ('63', 'Şanlıurfa'), ('64', 'Uşak'), ('65', 'Van'), ('77', 'Yalova'), ('66', 'Yozgat'), ('67', 'Zonguldak')], default='1', max_length=20, verbose_name='Adres Şehri'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email Adresi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905553332211', max_length=13, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_position',
            field=models.BooleanField(default=True, verbose_name='Öğrenci Konumu'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_regday',
            field=models.DateTimeField(default=person_panel.models.get_time, verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_town',
            field=models.CharField(default='', max_length=20, verbose_name='Adres İlçesi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_type',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Geçici'), ('2', 'Misafir')], default='1', max_length=10, verbose_name='Öğrenci Türü'),
        ),
    ]
