# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import person_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0011_auto_20170730_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_endday',
            field=models.DateField(default='', max_length=15, null=True, verbose_name='İşten Ayrılma Günü'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_startday',
            field=models.DateField(default=person_panel.models.get_date, max_length=15, verbose_name='İşe Başlangıç Tarihi'),
        ),
    ]
