# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import person_panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0012_auto_20170731_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfomodel',
            old_name='file_field',
            new_name='image_field',
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_endday',
            field=models.DateField(blank=True, default='', max_length=10, null=True, verbose_name='İşten Ayrılma Günü'),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='personal_startday',
            field=models.DateField(default=person_panel.models.get_date, max_length=10, verbose_name='İşe Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='personidinfomodel',
            name='s_birthday',
            field=models.DateField(default='1990-12-31', max_length=10, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='student_regday',
            field=models.DateField(default=person_panel.models.get_date, max_length=10, verbose_name='Kayıt Tarihi'),
        ),
    ]
