# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_panel', '0013_auto_20170731_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='image_field',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pic/', verbose_name='Profil Resmi'),
        ),
    ]
