# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfoModel',
            fields=[
                ('account_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account No: ')),
                ('account_name', models.CharField(max_length=10, verbose_name='Account Name: ')),
                ('account_type', models.CharField(max_length=10, verbose_name='Account Type: ')),
                ('account_amount', models.CharField(blank=True, max_length=10, verbose_name='Account Amount: ')),
                ('account_desc', models.CharField(blank=True, max_length=10, verbose_name='Account Description: ')),
            ],
        ),
        migrations.CreateModel(
            name='BillInfoModel',
            fields=[
                ('bill_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Bill No: ')),
                ('bill_type', models.CharField(max_length=10, verbose_name='Bill Type: ')),
                ('bill_code', models.CharField(max_length=10, verbose_name='Bill Code: ')),
                ('bill_desc', models.CharField(default='-', max_length=100, verbose_name='Bill Description: ')),
                ('bill_address', models.CharField(default='-', max_length=100, verbose_name='Bill Adress: ')),
                ('bill_period', models.CharField(default='-', max_length=10, verbose_name='Bill Period: ')),
                ('bill_last_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssetInfoModel',
            fields=[
                ('asset_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Individual Asset ID: ')),
                ('person_id', models.CharField(max_length=10, verbose_name='Person ID: ')),
                ('asset_amount', models.CharField(max_length=10, verbose_name='Asset Amount: ')),
                ('asset_debt', models.CharField(max_length=10, verbose_name='Asset Debt: ')),
                ('asset_desc', models.CharField(max_length=50, verbose_name='Asset Description: ')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInfoModel',
            fields=[
                ('transaction_no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Transaction No: ')),
                ('account_no', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_type', models.CharField(max_length=10, verbose_name='Transaction Type: ')),
                ('transaction_amount', models.CharField(max_length=10, verbose_name='Transaction Amount: ')),
                ('transaction_debit_credit', models.CharField(choices=[('1', 'debitin'), ('2', 'creditout')], default='1', max_length=10, verbose_name='Transaction is Debit or Credit: ')),
                ('transaction_time', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction_desc', models.CharField(blank=True, max_length=50, verbose_name='Transaction Description: ')),
            ],
        ),
    ]
