# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:40
from __future__ import unicode_literals

import account_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfoModel',
            fields=[
                ('no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('type', models.CharField(choices=[('1', 'Vadesiz Banka Hesabı'), ('2', 'Vadeli Banka Hesabı'), ('3', 'Nakit'), ('4', 'Senet'), ('5', 'Çek'), ('6', 'Kredi Kartı Hesabı')], max_length=40)),
                ('amount', models.CharField(default='', max_length=10)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(choices=[('149', 'HalkBank'), ('150', 'Vakıfbank'), ('151', 'Yapı Kredi'), ('152', 'Ziraat'), ('153', 'İş bankası'), ('154', 'Akbank')], max_length=5)),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='BillInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Su'), ('2', 'Doğalgaz'), ('3', 'Elektrik'), ('4', 'Internet'), ('5', 'Telefon'), ('6', 'Vergi')], max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
                ('amount', models.CharField(default='', max_length=10)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('period', models.CharField(default='', max_length=10)),
                ('last_day', models.DateField(default=account_panel.models.get_date, max_length=10)),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bill_info',
            },
        ),
        migrations.CreateModel(
            name='PersonAssetInfoModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=20)),
                ('amount', models.CharField(default='0', max_length=5)),
                ('debt', models.CharField(default='', max_length=5)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(default='', max_length=2)),
                ('type', models.CharField(choices=[('1', 'Nakit'), ('2', 'Kredi Kartı'), ('3', 'Para Transferi'), ('4', 'Online Ödeme')], max_length=10)),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'personasset_info',
            },
        ),
        migrations.CreateModel(
            name='TransactionInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('1', 'Para Yatırma'), ('2', 'Para Çekme'), ('3', 'Havale'), ('4', 'EFT'), ('5', 'Kredi Kartı Borcu Ödeme'), ('6', 'Fatura Ödeme'), ('7', 'Öğrenci Ödemesi')], default='1', max_length=10)),
                ('amount', models.CharField(default='', max_length=10)),
                ('time', models.DateTimeField(default='')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'transaction_info',
            },
        ),
    ]
