# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:58
from __future__ import unicode_literals

import account_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfoModel',
            fields=[
                ('no', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account No: ')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Account Name: ')),
                ('type', models.CharField(choices=[('1', 'Vadesiz Banka Hesabı'), ('2', 'Vadeli Banka Hesabı'), ('3', 'Nakit'), ('4', 'Senet'), ('5', 'Çek'), ('6', 'Kredi Kartı Hesabı')], max_length=40, verbose_name='Account Type: ')),
                ('amount', models.CharField(default='', max_length=10, verbose_name='Account Amount: ')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Description: ')),
                ('bank_code', models.CharField(choices=[('149', 'HalkBank'), ('150', 'Vakıfbank'), ('151', 'Yapı Kredi'), ('152', 'Ziraat Bankası'), ('153', 'İş Bankası'), ('154', 'Akbank')], max_length=20, verbose_name='Account Bank')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'account_info',
            },
        ),
        migrations.CreateModel(
            name='BillInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Su'), ('2', 'Doğalgaz'), ('3', 'Elektrik'), ('4', 'Internet'), ('5', 'Telefon'), ('6', 'Vergi')], max_length=10, verbose_name='Bill Type: ')),
                ('code', models.CharField(default='', max_length=10, verbose_name='Bill Code: ')),
                ('amount', models.CharField(default='', max_length=10, verbose_name='Bill Amount: ')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bill Description: ')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bill Adress: ')),
                ('period', models.CharField(default='', max_length=10, verbose_name='Bill Period: ')),
                ('last_day', models.DateField(default=account_panel.models.get_date, max_length=10)),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bill_info',
            },
        ),
        migrations.CreateModel(
            name='PersonAssetInfoModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Ödeme Planı Numarası: ')),
                ('person', models.CharField(max_length=10)),
                ('amount', models.CharField(default='', max_length=5, verbose_name='Asset Amount: ')),
                ('debt', models.CharField(default='', max_length=5, verbose_name='Asset Debt: ')),
                ('desc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Asset Description: ')),
                ('period', models.CharField(blank=True, default='', max_length=2)),
                ('type', models.CharField(blank=True, choices=[('1', 'Nakit'), ('2', 'Kredi Kartı'), ('3', 'Para Transferi'), ('4', 'Online Ödeme')], max_length=10, verbose_name='Asset Type')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'personasset_info',
            },
        ),
        migrations.CreateModel(
            name='TransactionInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('', ''), ('1', 'Para Yatırma'), ('2', 'Para Çekme'), ('3', 'Havale'), ('4', 'EFT'), ('5', 'Kredi Kartı Borcu Ödeme'), ('6', 'Fatura Ödeme'), ('7', 'Öğrenci Ödemesi')], default='1', max_length=10, verbose_name='İşlem Türü')),
                ('amount', models.CharField(default='', max_length=10, verbose_name='İşlem Miktarı')),
                ('time', models.DateTimeField(default='', verbose_name='İşlem Zamanı')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='İşlem Açıklaması')),
                ('company_id', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transaction_info',
            },
        ),
    ]
