# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0002_auto_20170710_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='account_no',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account_panel.AccountInfoModel', verbose_name='Account No:'),
            preserve_default=False,
        ),
    ]
