# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0002_auto_20171030_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Para Yatırma'), ('2', 'Para Çekme'), ('3', 'Havale'), ('4', 'EFT'), ('5', 'Kredi Kartı Borcu Ödeme'), ('6', 'Fatura Ödeme'), ('7', 'Öğrenci Ödemesi'), ('8', 'Maaş')], default='1', max_length=10),
        ),
    ]
