# Generated by Django 2.0.1 on 2018-01-16 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0002_auto_20180114_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='0',
            new_name='deposito',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='1',
            new_name='month1',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='10',
            new_name='month10',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='11',
            new_name='month11',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='12',
            new_name='month12',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='2',
            new_name='month2',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='3',
            new_name='month3',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='4',
            new_name='month4',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='5',
            new_name='month5',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='6',
            new_name='month6',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='7',
            new_name='month7',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='8',
            new_name='month8',
        ),
        migrations.RenameField(
            model_name='periodicpaymentmodel',
            old_name='9',
            new_name='month9',
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 23, 7, 0, 708122)),
        ),
    ]
