# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0003_auto_20171003_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='person',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='account_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
