# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0003_auto_20170711_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_desc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Account Description: '),
        ),
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_name',
            field=models.CharField(max_length=20, verbose_name='Account Name: '),
        ),
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_type',
            field=models.CharField(choices=[('1', 'Vadesiz Banka Hesab\u0131'), ('2', 'Vadeli Banka Hesab\u0131'), ('3', 'Nakit'), ('4', 'Senet'), ('5', '\xc7ek'), ('6', 'Kredi Kart\u0131 Hesab\u0131')], max_length=40, verbose_name='Account Type: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel', verbose_name='Person id'),
        ),
    ]
