# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0004_auto_20170711_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinfomodel',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='transactioninfomodel',
            name='transaction_no',
        ),
        migrations.AddField(
            model_name='billinfomodel',
            name='id',
            field=models.AutoField(auto_created=True, default='1713001', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioninfomodel',
            name='id',
            field=models.AutoField(auto_created=True, default='1714001', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
