# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0005_auto_20171003_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfomodel',
            name='bank_code',
            field=models.CharField(choices=[('149', 'HalkBank'), ('150', 'Vakıfbank'), ('151', 'Yapı Kredi'), ('152', 'Ziraat Bankası'), ('153', 'İş Bankası'), ('154', 'Akbank')], max_length=5, verbose_name='Account Bank'),
        ),
    ]
