# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0006_auto_20171005_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfomodel',
            name='bank_code',
            field=models.CharField(choices=[('149', 'HalkBank'), ('150', 'Vakıfbank'), ('151', 'Yapı Kredi'), ('152', 'Ziraat'), ('153', 'İş bankası'), ('154', 'Akbank')], max_length=5),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='amount',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='debt',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='period',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person_panel.StudentInfoModel'),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Nakit'), ('2', 'Kredi Kartı'), ('3', 'Para Transferi'), ('4', 'Online Ödeme')], max_length=10),
        ),
    ]
