# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0006_auto_20170711_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioninfomodel',
            name='transaction_debit_credit',
        ),
        migrations.AddField(
            model_name='billinfomodel',
            name='bill_amount',
            field=models.CharField(default='0', max_length=10, verbose_name='Bill Amount: '),
            preserve_default=False,
        ),
    ]
