# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0007_auto_20170711_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinfomodel',
            old_name='bill_last_date',
            new_name='bill_lastday',
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_period',
            field=models.CharField(blank=True, max_length=10, verbose_name='Asset period, payment time'),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Asset Type'),
        ),
    ]
