# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0007_auto_20171007_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='amount',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
