# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0009_accountinfomodel_account_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioninfomodel',
            name='person_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Öğrencinin Numarası'),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='account_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_panel.AccountInfoModel', verbose_name='Hesap Numarası'),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_amount',
            field=models.CharField(max_length=10, verbose_name='İşlem Miktarı'),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_desc',
            field=models.CharField(blank=True, max_length=50, verbose_name='İşlem Açıklaması'),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='İşlem Zamanı'),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'Para Yatırma'), ('2', 'Para Çekme'), ('3', 'Havale'), ('4', 'EFT'), ('5', 'Kredi Kartı Borcu Ödeme'), ('6', 'Fatura Ödeme'), ('7', 'Tahsilat'), ('8', 'Öğrenci Ödemesi')], default='1', max_length=10, verbose_name='İşlem Türü'),
        ),
    ]
