# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0009_auto_20171009_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='type',
            field=models.CharField(choices=[('1', 'Para Yatırma'), ('2', 'Para Çekme'), ('3', 'Havale'), ('4', 'EFT'), ('5', 'Kredi Kartı Borcu Ödeme'), ('6', 'Fatura Ödeme'), ('7', 'Öğrenci Ödemesi')], default='1', max_length=10),
        ),
    ]
