# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0010_auto_20171021_1534'),
        ('account_panel', '0010_auto_20171021_1405'),
    ]

    operations = [
    ]
