# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0010_auto_20170715_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='person_id',
            field=models.CharField(blank=True, choices=[('1701001', 'asf klkl'), ('1701002', 'dsvasf sadafd'), ('1701003', 'Ahmet Yilmaz')], max_length=50, verbose_name='Öğrencinin Numarası'),
        ),
    ]
