# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0011_auto_20170715_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioninfomodel',
            name='person_id',
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_desc',
            field=models.CharField(blank=True, help_text='Öğrenci No:1701001 /Fatura No: 1713001', max_length=50, verbose_name='İşlem Açıklaması'),
        ),
    ]
