# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0012_auto_20170715_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_period',
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_type',
            field=models.CharField(choices=[('1', 'Su'), ('2', 'Doğalgaz'), ('3', 'Elektrik'), ('4', 'Internet'), ('5', 'Telefon'), ('1', 'Vergi'), ('1', 'İSKİ'), ('1', 'İSKİ')], max_length=10, verbose_name='Bill Type: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('1', 'Nakit'), ('2', 'Kredi Kartı'), ('3', 'Para Transferi'), ('4', 'Online Ödeme')], max_length=10, verbose_name='Asset Type'),
        ),
    ]
