# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0014_auto_20170719_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_eight',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_eleven',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_five',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_four',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_nine',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_one',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_seven',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_six',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_ten',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_three',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_twelve',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_two',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_lastday',
            field=models.DateField(default='2017-07-20'),
        ),
    ]
