# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:00
from __future__ import unicode_literals

import account_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0015_auto_20170720_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_eight',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_eleven',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_five',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_four',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_nine',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_one',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_seven',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_six',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_ten',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_three',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_twelve',
        ),
        migrations.RemoveField(
            model_name='personassetinfomodel',
            name='asset_two',
        ),
        migrations.AddField(
            model_name='personassetinfomodel',
            name='asset_period',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_lastday',
            field=models.DateField(default=account_panel.models.get_time),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_time',
            field=models.DateTimeField(default=account_panel.models.get_time, verbose_name='İşlem Zamanı'),
        ),
    ]
