# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:54
from __future__ import unicode_literals

import account_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0016_auto_20170721_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_lastday',
            field=models.DateTimeField(default=account_panel.models.get_time),
        ),
    ]
