# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0017_auto_20170721_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_period',
            field=models.CharField(default='', max_length=10, verbose_name='Bill Period: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_amount',
            field=models.CharField(default='0', max_length=10, verbose_name='Asset Amount: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_debt',
            field=models.CharField(default='10000', max_length=10, verbose_name='Asset Debt: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_period',
            field=models.CharField(blank=True, default='10', max_length=2),
        ),
    ]
