# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0018_auto_20170723_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_amount',
            field=models.CharField(default='', max_length=10, verbose_name='Account Amount: '),
        ),
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_bank',
            field=models.CharField(choices=[('149', 'Suadiye-HalkBank')], max_length=20, verbose_name='Account Bank'),
        ),
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_desc',
            field=models.CharField(default='', max_length=100, verbose_name='Account Description: '),
        ),
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_name',
            field=models.CharField(default='', max_length=20, verbose_name='Account Name: '),
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_address',
            field=models.CharField(default='', max_length=200, verbose_name='Bill Adress: '),
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_amount',
            field=models.CharField(default='', max_length=10, verbose_name='Bill Amount: '),
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_code',
            field=models.CharField(default='', max_length=10, verbose_name='Bill Code: '),
        ),
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_desc',
            field=models.CharField(default='', max_length=100, verbose_name='Bill Description: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_desc',
            field=models.CharField(default='', max_length=50, verbose_name='Asset Description: '),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_amount',
            field=models.CharField(default='', max_length=10, verbose_name='İşlem Miktarı'),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_desc',
            field=models.CharField(default='', max_length=50, verbose_name='İşlem Açıklaması'),
        ),
    ]
