# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0019_auto_20170723_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_desc',
            field=models.CharField(default='', max_length=100, verbose_name='İşlem Açıklaması'),
        ),
    ]
