# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0020_auto_20170723_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_amount',
            field=models.CharField(default='', max_length=5, verbose_name='Asset Amount: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_debt',
            field=models.CharField(default='', max_length=5, verbose_name='Asset Debt: '),
        ),
        migrations.AlterField(
            model_name='personassetinfomodel',
            name='asset_period',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
