# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0021_auto_20170729_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfomodel',
            name='account_bank',
            field=models.CharField(choices=[('149', 'HalkBank'), ('150', 'Vakıfbank'), ('151', 'Yapı Kredi'), ('152', 'Ziraat Bankası'), ('153', 'İş Bankası'), ('154', 'Akbank')], max_length=20, verbose_name='Account Bank'),
        ),
    ]
