# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:01
from __future__ import unicode_literals

import account_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_panel', '0022_auto_20170730_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinfomodel',
            name='bill_lastday',
            field=models.DateField(default=account_panel.models.get_date, max_length=10),
        ),
        migrations.AlterField(
            model_name='transactioninfomodel',
            name='transaction_desc',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='İşlem Açıklaması'),
        ),
    ]
